Superhero.create("name"=>"Batman", "city"=>"Gothem", "superpower"=>"Gadgets", "superscore"=>0.3)
Superhero.create("name"=>"Superman", "city"=>"Krypton", "superpower"=>"Super Strengh", "superscore"=>0.8)
Superhero.create("name"=>"Hulk", "city"=>"New York", "superpower"=>"Super Strengh", "superscore"=>0.1)
Superhero.create("name"=>"Iron Man", "city"=>"Malibu", "superpower"=>"Smart", "superscore"=>0.5)
Superhero.create("name"=>"Thor", "city"=>"Galaxies", "superpower"=>"Thunder", "superscore"=>0.8)
Superhero.create("name"=>"Spiderman", "city"=>"New York", "superpower"=>"SpiderWeb", "superscore"=>0.5)
Superhero.create("name"=>"Captain America", "city"=>"Kentucky", "superpower"=>"Super Strengh", "superscore"=>0.6)
Superhero.create("name"=>"Arrow", "city"=>"Stardom", "superpower"=>"Arrows", "superscore"=>0.4)
Superhero.create("name"=>"Flash", "city"=>"Stardom", "superpower"=>"Super Fast", "superscore"=>0.5)
Superhero.create("name"=>"Black Widow", "city"=>"Moscow", "superpower"=>"Agility", "superscore"=>0.5)
Superhero.create("name"=>"Wolvarine", "city"=>"Atlanta", "superpower"=>"Claws of Steel", "superscore"=>0.7)
Superhero.create("name"=>"Magnito", "city"=>"Mississippi", "superpower"=>"Manipulates Metal", "superscore"=>0.7)